definitions:
  service.Career:
    properties:
      position:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /careers:
    get:
      description: Returns list of careers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Career'
      summary: Get Careers
      tags:
      - GetCareers
swagger: "2.0"
