basePath: /
definitions:
  Router.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  service.Career:
    properties:
      position:
        type: string
      title:
        type: string
    type: object
host: localhost:8095
info:
  contact: {}
  description: This is the API documentation for my backend
  title: My API
  version: "1.0"
paths:
  /careers:
    get:
      description: Returns list of careers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Career'
      summary: Get Careers
      tags:
      - GetCareers
  /login:
    post:
      consumes:
      - application/json
      description: Allows user to login
      parameters:
      - description: Login Credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/Router.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - Login
swagger: "2.0"
